"""Precompute the spectra the interactive explorer page interpolates between.

The page at ``docs/index.html`` lets a reader drag grain size, pond depth and
impurity load and watch the spectrum move, with Sentinel-2's ten bands drawn on
top of Tanager's 221. Everything it plots comes from the same ``forward`` module
the retrieval is trained on -- the page is a window onto the real forward model,
not a redrawing of it.

Endmembers are precomputed on a grid and mixed in the browser, because mixing is
linear in the fractions: shipping the three endmember grids is far smaller than
shipping every combination. Reflectance is stored as an integer per mil to keep
the payload small; the page divides by 1000.

Usage
-----
    PYTHONPATH=3_src python -m tanager_cryo.export_explorer
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from . import forward as F, s2compare, synth

ROOT = Path(__file__).resolve().parents[2]

MU0 = 0.624  # cos(solar zenith) for the Sirmilik scene

# Grids. Ranges match the training priors in synth.py so the page cannot show a
# state the retrieval was never trained on.
LOG_L = np.linspace(*synth.LOG_L_RANGE, 21)
LAP = np.linspace(*synth.LAP_RANGE, 5)
DEPTH = np.linspace(*synth.POND_DEPTH_RANGE, 13)


def per_mil(a: np.ndarray) -> list:
    """Reflectance -> integer per mil, clipped to a sane display range."""
    return np.clip(np.round(np.asarray(a) * 1000.0), 0, 1200).astype(int).tolist()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=ROOT / "docs" / "spectra.json")
    args = ap.parse_args()

    wl, _, _ = synth.load_band_selection()
    print(f"{wl.size} bands, {wl.min():.0f}-{wl.max():.0f} nm")

    # Solid surface: snow/ice over the grain-size x impurity grid.
    solid = [[per_mil(F.snow_reflectance(wl, 10.0**L, mu0=MU0, lap_load=p))
              for p in LAP] for L in LOG_L]

    # Melt pond: a water column over a scattering floor whose path length is tied
    # to the surrounding ice, exactly as synth.generate does it.
    pond = [[per_mil(F.melt_pond_reflectance(
        wl, d, bottom_absorption_length_m=min(10.0**L * 8.0, 5e-2), mu0=MU0))
        for d in DEPTH] for L in LOG_L]

    water = per_mil(F.open_water_reflectance(wl))

    # Sentinel-2 convolution as a 221 x 10 weight matrix, so the page can degrade
    # whatever spectrum it is currently showing rather than interpolating a
    # second precomputed grid.
    srf_wl, srf, names = s2compare.load_srf()
    w = np.empty((wl.size, len(names)))
    for j in range(len(names)):
        w[:, j] = np.interp(wl, srf_wl, srf[:, j], left=0.0, right=0.0)
    w = w / np.clip(w.sum(axis=0, keepdims=True), 1e-12, None)
    centres = (w * wl[:, None]).sum(axis=0)

    payload = {
        "wavelength_nm": np.round(wl, 1).tolist(),
        "mu0": MU0,
        "axes": {
            "log10_absorption_length_m": np.round(LOG_L, 3).tolist(),
            "lap_load": np.round(LAP, 1).tolist(),
            "pond_depth_m": np.round(DEPTH, 3).tolist(),
        },
        "solid_per_mil": solid,      # [L][lap][band]
        "pond_per_mil": pond,        # [L][depth][band]
        "water_per_mil": water,      # [band]
        "sentinel2": {
            "bands": list(names),
            "centre_nm": np.round(centres, 1).tolist(),
            "weights": np.round(w, 6).tolist(),   # [band][s2band]
        },
        "provenance": {
            "forward_model": "Kokhanovsky-Zege ART; Warren & Brandt (2008) ice; "
                             "Segelstein (1981) water",
            "srf": "ESA Sentinel-2A, COPE-GSEG-EOPG-TN-15-0007",
            "note": "generated by tanager_cryo.export_explorer from the same "
                    "forward model the retrieval is trained on",
        },
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(payload, separators=(",", ":")))
    print(f"wrote {args.out}  ({args.out.stat().st_size / 1e3:.0f} kB)")


if __name__ == "__main__":
    main()
