"""Synthetic training-set generation for the cryosphere retrieval emulator.

There is no in-situ ground truth at Sirmilik on 2025-06-06 — no buoys, no field
campaign, no coincident aerial survey. Training a retrieval on labels we do not have
would be dishonest. Instead we train on spectra generated by the forward model in
``forward.py``, which is the standard approach for spaceborne cryosphere retrieval when
validation data are absent, and we carry the instrument's own uncertainty through the
noise model so the network learns how much to trust each band.

The noise model is not white. It is drawn from the per-band reflectance uncertainty that
Tanager ships alongside every scene, which for snow and ice rises from ~0.5% relative in
the visible to >10% beyond 2100 nm, where ice absorption drives the signal to zero. A
network trained under this noise learns to weight 400-1300 nm and largely ignore the
SWIR, without that preference ever being hard-coded.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from . import forward as F

_DATA = Path(__file__).resolve().parents[2] / "1_data" / "optical_constants"

# Retrieved quantities, in the order the network emits them.
#
# Snow and bare ice are deliberately *one* endmember. They are the same material
# separated only by photon path length, so a parameterisation carrying both a snow
# fraction and an ice fraction alongside a free absorption length is degenerate:
# f_snow * R(L) + f_ice * R(12L) is nearly indistinguishable from a single component at
# some intermediate L. A first pass with the split parameterisation confirmed this
# directly -- pond and water fractions were recovered well (RMSE 0.08 and 0.26 in
# standard units) while snow and ice sat at 0.69 and 0.74, i.e. barely better than
# predicting the prior mean.
#
# Collapsing them removes the degeneracy and is the better physics: grain size becomes a
# continuous retrieved quantity spanning fine dry snow to coarse decaying ice, rather
# than a discrete class label imposed on a continuum.
PARAM_NAMES = (
    "f_solid",  # snow + bare ice, characterised by absorption length
    "f_pond",
    "f_water",
    "log10_absorption_length_m",
    "pond_depth_m",
    "lap_load",
)

# Parameters that are only identifiable when their host endmember is present. Used for
# conditional evaluation: pond depth is meaningless in a pixel with no pond.
CONDITIONAL_PARAMS = {
    "log10_absorption_length_m": ("f_solid", 0.25),
    "pond_depth_m": ("f_pond", 0.25),
    "lap_load": ("f_solid", 0.25),
}

# Priors. The absorption length must span everything the scene contains, from fine dry
# snow (1e-4 m) to heavily decayed, large-crystal melting sea ice. A first pass capped
# this at 10^-1.5 m and the retrieval piled up against the ceiling: the median retrieved
# value sat at -1.646 with most pixels flagged outside the prior. Melting sea ice has a
# far longer photon path than dry snow, so the ceiling is raised to 10^-0.5 m.
LOG_L_RANGE = (-4.0, -0.5)
POND_DEPTH_RANGE = (0.02, 0.80)  # m; typical Arctic melt ponds are 0.1-0.5 m
LAP_RANGE = (0.0, 80.0)  # 1/m at 500 nm


@dataclass
class TrainingSet:
    reflectance: np.ndarray  # (n, n_bands) noisy
    uncertainty: np.ndarray  # (n, n_bands) 1-sigma used to perturb
    params: np.ndarray  # (n, n_params)
    wavelength: np.ndarray  # (n_bands,)
    band_index: np.ndarray  # indices into the original 426-band grid


# Minimum median signal-to-noise for a band to enter the retrieval. Chosen from the
# scene's own SNR spectrum: beyond ~1800 nm ice absorption drives snow and ice
# reflectance to the noise floor (SNR ~3-16 at 2000-2500 nm), while every absorption
# feature the retrieval depends on -- impurities at 400-600, pond depth at 660-810,
# ice grain size at 1030 and 1240, liquid water at 980 and 1200 nm -- sits below 1350 nm
# with SNR 55-235.
DEFAULT_SNR_THRESHOLD = 30.0


def load_band_selection(
    snr_threshold: float = DEFAULT_SNR_THRESHOLD,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return (wavelength, uncertainty_sigma, band_index) for the usable bands.

    Two filters are applied, both driven by data Tanager ships with the scene rather
    than by hand-picked wavelength windows:

    1. ``good_wavelengths == False`` removes the 1342-1438 and 1783-1967 nm
       water-vapour absorption regions, which carry no surface information.
    2. A median signal-to-noise cut, computed from the scene's own
       ``surface_reflectance_uncertainty`` layer, removes bands where the surface
       signal has fallen to the noise floor.

    The second filter is the point of the exercise: it is derived, not assumed, and it
    is what stops the SWIR noise from dominating a retrieval that weights all bands
    equally.
    """
    wl = np.load(_DATA / "tanager_wavelengths.npy").astype(float)
    sigma = np.load(_DATA / "tanager_uncertainty_median.npy").astype(float)
    good = np.load(_DATA / "tanager_good_wavelengths.npy").astype(bool)
    snr = np.load(_DATA / "tanager_snr_median.npy").astype(float)
    keep = good & (snr > snr_threshold)
    idx = np.where(keep)[0]
    return wl[idx], sigma[idx], idx


N_ENDMEMBERS = 3  # solid (snow/ice), melt pond, open water

# RMS amplitude of the smooth forward-model error injected during training, in reflectance.
# Measured, not guessed: reconstructing the Sirmilik scene from its own retrieved parameters
# leaves a residual whose robust per-band spread is 0.0285 (see residual.estimate_model_error).
MODEL_ERROR_RMS = 0.03

# Number of Legendre modes used to build that error. Low order on purpose: the mismatch
# between a three-endmember ART model and a real melting sea-ice surface is a smooth
# spectral shape error, not a per-band wobble.
MODEL_ERROR_MODES = 4


def smooth_model_error(
    wavelength: np.ndarray,
    n: int,
    rng: np.random.Generator,
    rms: float = MODEL_ERROR_RMS,
    modes: int = MODEL_ERROR_MODES,
) -> np.ndarray:
    """Draw smooth, spectrally correlated perturbations emulating forward-model error.

    Why this exists
    ---------------
    Training only against instrument noise produced a network that scored R^2 = 1.000 on
    synthetic spectra and then disagreed with same-day Sentinel-2 on the real scene, with
    the endmember fractions *anti*-correlated. The cause was a domain gap the synthetic
    evaluation could not see: Tanager's instrument sigma is 0.0013, but the forward model
    reproduces real sea-ice reflectance only to 0.0285. The network was being asked, at
    inference, to interpret spectra deviating from its training manifold by five times the
    largest noise it had ever been shown.

    White noise at that amplitude would be the wrong repair. It would teach the network to
    be uncertain, not to be robust, because forward-model error is not white: it is a
    smooth bias in spectral *shape* -- our model runs 0.03-0.06 dark through the visible
    and close to right in the near-infrared. So the perturbation is built from a handful of
    low-order Legendre polynomials over the band range, which is what such a shape error
    looks like, and scaled so its RMS matches the measured value.
    """
    wl = np.asarray(wavelength, dtype=float)
    t = 2.0 * (wl - wl.min()) / (wl.max() - wl.min()) - 1.0  # map to [-1, 1]

    basis = np.empty((modes, wl.size))
    for k in range(modes):
        c = np.zeros(k + 2)
        c[k + 1] = 1.0
        basis[k] = np.polynomial.legendre.legval(t, c)
    # Normalise each mode to unit RMS so the amplitude draw controls the total directly.
    basis /= np.sqrt((basis**2).mean(axis=1, keepdims=True))

    # Amplitude varies per sample: some pixels are well described by the model, some badly.
    amp = rng.uniform(0.0, 1.0, size=(n, 1)) * rms
    coef = rng.normal(0.0, 1.0, size=(n, modes)) / np.sqrt(modes)
    return ((coef * amp) @ basis).astype(np.float32)


def sample_fractions(rng: np.random.Generator, n: int) -> np.ndarray:
    """Draw endmember fractions from a Dirichlet weighted toward realistic scenes.

    A flat Dirichlet would make three-way mixtures typical, which they are not: most
    30 m pixels are dominated by one or two surfaces. The low concentration parameter
    pushes mass toward the simplex corners and edges.
    """
    return rng.dirichlet(np.full(N_ENDMEMBERS, 0.45), size=n)


def generate(
    n: int = 60_000,
    mu0: float = 0.624,
    seed: int = 0,
    noise_scale_range: tuple[float, float] = (0.4, 4.0),
    snr_threshold: float = DEFAULT_SNR_THRESHOLD,
) -> TrainingSet:
    """Generate a synthetic training set.

    Parameters
    ----------
    n
        Number of spectra.
    mu0
        Cosine of the solar zenith angle for the target scene.
    noise_scale_range
        Per-sample multiplier on the empirical Tanager uncertainty, drawn
        log-uniformly. Varying the noise level *across* samples is what makes the
        uncertainty input informative: a network trained at a single fixed noise level
        would learn to ignore it. Here the network sees noisy spectra paired with the
        sigma that produced them, and must learn to widen its own predictive variance
        when the instrument reports a poor measurement.
    """
    rng = np.random.default_rng(seed)
    wl, sigma, idx = load_band_selection(snr_threshold)
    nb = wl.size

    fr = sample_fractions(rng, n)
    log_L = rng.uniform(*LOG_L_RANGE, size=n)
    depth = rng.uniform(*POND_DEPTH_RANGE, size=n)
    lap = rng.uniform(*LAP_RANGE, size=n)

    clean = np.empty((n, nb), dtype=np.float32)
    water = F.open_water_reflectance(wl)

    for i in range(n):
        L = 10.0**log_L[i]
        solid = F.snow_reflectance(wl, L, mu0=mu0, lap_load=lap[i])
        # A pond sits on ice that has already coarsened, so its floor is given a longer
        # path than the surrounding solid surface rather than an independent free value.
        pond = F.melt_pond_reflectance(
            wl, depth[i], bottom_absorption_length_m=min(L * 8.0, 5e-2), mu0=mu0
        )
        clean[i] = F.mix(fr[i], np.vstack([solid, pond, water]))

    lo, hi = noise_scale_range
    scale = np.exp(rng.uniform(np.log(lo), np.log(hi), size=n)).astype(np.float32)
    sig = (sigma[None, :].astype(np.float32) * scale[:, None])
    noisy = clean + rng.normal(0.0, 1.0, size=clean.shape).astype(np.float32) * sig
    noisy = noisy + smooth_model_error(wl, n, rng, MODEL_ERROR_RMS)

    params = np.column_stack([fr, log_L, depth, lap]).astype(np.float32)
    return TrainingSet(
        reflectance=noisy,
        uncertainty=sig,
        params=params,
        wavelength=wl,
        band_index=idx,
    )
